<?xml version="1.0"?>
<package format="3">
  <name>robot_navigation</name>
  <version>3.0.0</version>
  <description>Nav2 navigation, AMCL localization, planner config, keepout filter and behavior trees.</description>
  <maintainer email="cldac@buyjustnow.com">damith</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_bringup</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
